(function initializeContent() {
  if (window.__oneClickAIReaderLoaded) return;
  window.__oneClickAIReaderLoaded = true;
  const host = document.createElement("div"); host.id = "one-click-ai-root";
  const shadow = host.attachShadow({ mode: "open" });
  shadow.innerHTML = `<style>
  :host{all:initial}.wrap{position:fixed;right:22px;bottom:22px;z-index:2147483646;font-family:Inter,system-ui,sans-serif;color:#172033}button,textarea{font:inherit}.fab{border:0;border-radius:999px;background:linear-gradient(135deg,#6d5dfc,#3a83f7);color:#fff;padding:12px 17px;font-weight:750;box-shadow:0 12px 32px #274bb847;cursor:grab}.panel{display:none;width:min(380px,calc(100vw - 28px));max-height:min(620px,calc(100vh - 80px));margin-bottom:10px;background:#fff;border:1px solid #e7e9f2;border-radius:18px;box-shadow:0 18px 60px #16204433;overflow:hidden}.panel.open{display:block}.head{display:flex;align-items:center;justify-content:space-between;padding:15px 17px;border-bottom:1px solid #edf0f6;font-weight:750}.close{border:0;background:transparent;font-size:20px;color:#70788b;cursor:pointer}.body{padding:17px;overflow:auto;max-height:430px}.status{font-size:13px;color:#647087;margin-bottom:10px}.answer{font-size:14px;line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere}.preview{width:100%;min-height:160px;max-height:270px;resize:vertical;border:1px solid #dfe3ed;border-radius:10px;padding:11px;color:#253047;background:#fafbfe;line-height:1.5}.privacy{font-size:11px;color:#788398;margin-top:10px}.actions{display:flex;gap:8px;padding:12px 17px;border-top:1px solid #edf0f6}.actions button{border:1px solid #dde2ed;background:#fff;border-radius:9px;padding:8px 10px;cursor:pointer}.actions .primary{margin-left:auto;border:0;background:#6758f6;color:#fff;font-weight:700}.progress{height:4px;background:#edf0f6;border-radius:9px;overflow:hidden}.progress:after{content:'';display:block;width:40%;height:100%;background:#6d5dfc;animation:load 1s infinite}.error{color:#b42318}.answer-key{display:grid;place-items:center;width:58px;height:58px;margin:8px auto;border-radius:18px;background:#eeeaff;color:#5849da;font-size:28px;font-weight:850}@media(prefers-color-scheme:dark){.panel{background:#171a23;border-color:#2b3040;color:#f3f5fb}.head,.actions{border-color:#2b3040}.actions button,.preview{background:#222633;color:#f3f5fb;border-color:#394052}.status,.privacy{color:#aeb7cb}}@keyframes load{from{transform:translateX(-110%)}to{transform:translateX(300%)}}</style>
  <div class="wrap"><section class="panel" aria-live="polite"><header class="head"><span>✦ AI Question</span><button class="close">×</button></header><div class="body"><div class="status">Select a question area to begin.</div><div class="answer">Only the selected question area will be analyzed.</div></div><footer class="actions"></footer></section><button class="fab">✦ Select Question</button></div>`;
  document.documentElement.appendChild(host);
  const wrap=shadow.querySelector(".wrap"),panel=shadow.querySelector(".panel"),body=shadow.querySelector(".body"),status=shadow.querySelector(".status"),actions=shadow.querySelector(".actions"),fab=shadow.querySelector(".fab");
  let selection=null,lastPayload=null,moved=false,drag=null;
  if (window.top !== window) fab.style.display="none";
  const button=(label,action,primary=false)=>`<button data-action="${action}" class="${primary?"primary":""}">${label}</button>`;
  function bind(){actions.onclick=(event)=>{const action=event.target.closest("[data-action]")?.dataset.action;if(action==="cancel"){selection=null;panel.classList.remove("open");}if(action==="recapture"){panel.classList.remove("open");window.AIReaderSelectionMode.start();}if(action==="expand"&&selection?.suggestion)preview(selection.suggestion);if(action==="ask")ask();if(action==="retry")ask(lastPayload);if(action==="copy")navigator.clipboard.writeText(body.innerText||"");if(action==="explain")ask({...lastPayload,explainMore:true});};}
  function showReady(message="Only the selected question area will be analyzed."){host.style.visibility="visible";panel.classList.add("open");status.textContent="Ready";body.innerHTML='<div class="answer"></div>';body.firstChild.textContent=message;actions.innerHTML=button("Select Question","recapture",true);bind();}
  function showError(message,selectionError=false){host.style.visibility="visible";panel.classList.add("open");status.textContent="Unable to continue";body.innerHTML='<div class="answer error"></div>';body.firstChild.textContent=message;actions.innerHTML=button("Capture Again","recapture")+(selectionError?"":button("Retry","retry",true));bind();}
  function preview(data){selection=data;host.style.visibility="visible";panel.classList.add("open");status.textContent=data.suggestion?"Suggested Question Area available":data.readable?"Question captured · text extracted locally":"Question captured · image will be used";body.innerHTML='<textarea class="preview" aria-label="Extracted question" placeholder="No readable text found. The selected image will be analyzed."></textarea><div class="privacy">Only this selected content will be sent after you press Ask AI.</div>';body.querySelector("textarea").value=data.text;actions.innerHTML=button("Cancel","cancel")+(data.suggestion?button("Expand to Question","expand"):button("Capture Again","recapture"))+button("Ask AI ✦","ask",true);bind();}
  async function ask(payload){if(!payload){const text=body.querySelector("textarea")?.value.trim()||"";payload={...selection,text,readable:window.AIReaderQuestion.readable(text)};}if(!payload?.rect)return showError("Capture a question area first.",true);lastPayload=payload;status.textContent=payload.readable&&!payload.hasVisual?"✦ Extracting question...":"✦ Reading selected area...";body.innerHTML='<div class="progress"></div>';actions.innerHTML="";const response=await chrome.runtime.sendMessage({type:"ANALYZE_SELECTION",payload}).catch((e)=>({ok:false,error:e.message}));if(response?.ok)renderResult(response.item);else showError(response?.error||"Unable to analyze the selected question.");}
  function renderResult(item){host.style.visibility="visible";panel.classList.add("open");status.textContent="✦ AI Analysis";const answer=item.answer||"",match=answer.match(/ANSWER:\s*([^\n]+)/i);body.innerHTML=`${match?'<div class="answer-key"></div>':""}<div class="answer"></div>`;if(match)body.querySelector(".answer-key").textContent=match[1].trim();body.querySelector(".answer").textContent=answer;actions.innerHTML=button("Copy","copy")+button("Explain More","explain",true);bind();}
  window.AIReaderUI={preview,showError,showReady,renderResult};
  fab.addEventListener("pointerdown",(e)=>{moved=false;drag={x:e.clientX,y:e.clientY,right:innerWidth-wrap.getBoundingClientRect().right,bottom:innerHeight-wrap.getBoundingClientRect().bottom};fab.setPointerCapture(e.pointerId);});fab.addEventListener("pointermove",(e)=>{if(!drag)return;if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)>5)moved=true;wrap.style.right=Math.max(8,drag.right-(e.clientX-drag.x))+"px";wrap.style.bottom=Math.max(8,drag.bottom-(e.clientY-drag.y))+"px";});fab.addEventListener("pointerup",()=>{drag=null;if(!moved){panel.classList.remove("open");window.AIReaderSelectionMode.start();}});shadow.querySelector(".close").onclick=()=>panel.classList.remove("open");
  chrome.storage.local.get("settings").then(({settings})=>{host.style.display=settings?.floatingButton===false?"none":"block";});chrome.storage.onChanged.addListener((changes)=>{if(changes.settings)host.style.display=changes.settings.newValue?.floatingButton===false?"none":"block";});chrome.runtime.onMessage.addListener((message,_sender,respond)=>{if(message.type==="PING"){respond({ready:true});return;}if(message.type==="START_SELECTION"){panel.classList.remove("open");window.AIReaderSelectionMode.start();respond({ok:true});return;}if(message.type==="PREPARE_REGION_CAPTURE"){host.style.visibility="hidden";respond({ready:true});return;}if(message.type==="REGION_CAPTURED"){host.style.visibility="visible";respond({ready:true});return;}if(message.type==="AI_ANALYZING")status.textContent="✦ Analyzing...";if(message.type==="AI_RESULT")renderResult(message.item);if(message.type==="AI_ERROR")showError(message.error);});
})();
